// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#define X 16
#define Y 16

Texture2D SourceTexture1;
Texture2D SourceTexture2;

RWTexture2D<float4> TargetTexture;

int Width;
int Height;

[numthreads(X,Y,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= Width || id.y >= Height) return;
    uint2 depth_pos = uint2(id.x, id.y + Height);
    if (SourceTexture1[depth_pos].r < SourceTexture2[depth_pos].r)
    {
        TargetTexture[id.xy] = SourceTexture1[id.xy];
        TargetTexture[depth_pos] = SourceTexture1[depth_pos];
    }
    else
    {
        TargetTexture[id.xy] = SourceTexture2[id.xy];
        TargetTexture[depth_pos] = SourceTexture2[depth_pos];
    }
}
