// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float4x4 ColorMatrix;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4x4 mat = 0;
    mat[0][0] = 0.5;
    mat[1][1] = 0.5;
    mat[2][2] = 0;
    mat[3][3] = 1;
    Result[id.xy] = float4(mat[0][0], mat[1][1], mat[2][2], mat[3][3]);
}
